import turtle

mohith = turtle.Screen()

mohith.title("undercontrol")
mohith.setup(1200,700)
mohith.listen()

mario = turtle.Turtle()
obstacle = turtle.Turtle()
obstacle1 = turtle.Turtle()
obstacle2 = turtle.Turtle()
obstacle3 = turtle.Turtle()
obstacle4 = turtle.Turtle()
obstacle5 = turtle.Turtle()
clouds = turtle.Turtle()
clouds1 = turtle.Turtle()
clouds2 = turtle.Turtle()
clouds3 = turtle.Turtle()
clouds4 = turtle.Turtle()
clouds5 = turtle.Turtle()

mario.shape("arrow")
mario.color("red")
mario.shapesize(1)
mario.penup()

obstacle.speed(12)
obstacle1.speed(12)
obstacle2.speed(12)
obstacle3.speed(12)
obstacle4.speed(12)
obstacle5.speed(12)
clouds.speed(12)
clouds1.speed(12)
clouds2.speed(12)
clouds3.speed(12)
clouds4.speed(12)
clouds5.speed(12)

obstacle.color("yellow")
obstacle.shape("square")
obstacle.shapesize(stretch_wid=1,stretch_len=5)
obstacle.penup()

obstacle2.color("yellow")
obstacle2.shape("square")
obstacle2.shapesize(stretch_wid=1,stretch_len=5)
obstacle2.penup()

obstacle3.color("yellow")
obstacle3.shape("square")
obstacle3.shapesize(stretch_len=5,stretch_wid=1)
obstacle3.penup()

obstacle4.color("yellow")
obstacle4.shape("square")
obstacle4.shapesize(stretch_len=5,stretch_wid=9)
obstacle4.penup()

obstacle5.color("yellow")
obstacle5.shape("square")
obstacle5.shapesize(stretch_wid=9,stretch_len=5)
obstacle5.penup()

obstacle1.color("yellow")
obstacle1.shape("square")
obstacle1.shapesize(stretch_len=5,stretch_wid=1)
obstacle1.penup()

clouds.color("white")
clouds.shape("circle")
clouds.penup()

clouds1.color("white")
clouds1.shape("circle")
clouds1.penup()

clouds2.color("white")
clouds2.shape("circle")
clouds2.penup()

clouds3.color("white")
clouds3.shape("circle")
clouds3.penup()

clouds4.color("white")
clouds4.shape("circle")
clouds4.penup()

clouds5.color("white")
clouds5.shape("circle")
clouds5.penup()

mohith.bgcolor("blue")

def positionsofeverything():
  obstacle.goto(-325,-250)
  obstacle.forward(70)
  obstacle1.goto(-325,-250)
  obstacle1.forward(70)
  mario.goto(-325,-250)
  obstacle1.forward(200)
  obstacle.back(200)
  mario.backward(100)
  mario.back(35)
  mario.left(90)
  obstacle1.back(180)
  mario.forward(20)
  mario.right(90)
  obstacle1.left(90)
  obstacle1.forward(100)
  obstacle1.right(90)
  obstacle4.goto(-325,-250)
  obstacle4.forward(550)
  obstacle5.goto(-325,-250)
  obstacle5.forward(800)
  clouds.goto(250,280)
  clouds.dot(80)
  clouds1.goto(295,280)
  clouds1.dot(80)
  clouds2.goto(340,280)
  clouds2.dot(80)
  clouds3.goto(-250,280)
  clouds3.dot(80)
  clouds4.goto(-295,280)
  clouds4.dot(80)
  clouds5.goto(-340,280)
  clouds5.dot(80)

def mariojump():
    mario.left(90)
    mario.forward(115)
    mario.right(90)
    mario.forward(150)

def moveright():
    mario.forward(20)
    mohith.listen()

def moveleft():
    mario.backward(30)
    mohith.listen()

def mariopendown():
    mario.pendown()

def obstaclesforscreen2():
    if mario.xcor() > 1400:
        mario.goto(-325,-250)
        obstacle.goto(-325,-250)
        obstacle1.goto(-325,-250)
        obstacle2.goto(-325,-250)
        obstacle3.goto(-325,-250)
        obstacle4.goto(-325,-250)
        obstacle5.goto(-325,-250)
        obstacle.backward(50)
        obstacle1.backward(50)
        obstacle2.backward(50)
        obstacle3.backward(50)
        obstacle4.backward(50)
        obstacle5.backward(50)
        obstacle1.forward(150)
        obstacle2.forward(250)
        obstacle3.forward(400)
        obstacle4.forward(600)
        obstacle5.forward(750)
        obstacle1.shape("square")
        obstacle2.shape("square")
        obstacle3.shape("square")
        obstacle4.shape("square")
        obstacle5.shape("square")
        obstacle.shapesize(stretch_len=9,stretch_wid=5)
        obstacle1.shapesize(stretch_wid=5,stretch_len=9)
        obstacle2.shapesize(stretch_len=9,stretch_wid=5)
        obstacle3.shapesize(stretch_wid=5,stretch_len=9)
        obstacle4.shapesize(stretch_len=9,stretch_wid=5)
        obstacle5.shapesize(stretch_wid=5,stretch_len=9)
        obstacle.back(120)
        obstacle1.back(80)
        obstacle.right(90)
        obstacle1.right(90)
        obstacle2.forward(30)
        obstacle3.forward(30)
        obstacle4.forward(70)
        obstacle5.forward(60)
        mario.showturtle()
        mario.back(100)
        mario.left(90)
        mario.forward(101)
        mario.right(90)
        mario.back(40)
        obstacle.showturtle()
        obstacle1.showturtle()
        obstacle2.showturtle()
        obstacle3.showturtle()
        obstacle4.showturtle()
        obstacle5.showturtle()

def controlls():
    mohith.onkey(moveleft,"Left")
    mohith.onkey(moveright,"Right")
    mohith.onkey(mariojump,"H")

mariojump()
controlls()
positionsofeverything()
moveleft()
moveright()
obstaclesforscreen2()
turtle.done()

#TODO
#i need to load screen 2
#i need to work on the gravity
#i need to work on the wall
#i need to work on the obstacles in screen 2
