import turtle
my_turtle=turtle.Turtle()
my_turtle.shape("turtle")
my_turtle.color("blue")
my_turtle.begin_fill()
my_turtle.forward(100)
my_turtle.right(90)

my_turtle.forward(100)
my_turtle.right(90)

my_turtle.forward(100)
my_turtle.right(90)
my_turtle.speed()
turtle.bgcolor("yellow")
my_turtle.forward(100)
my_turtle.end_fill()
my_turtle.right(90)
turtle.screensize(800,600)
my_turtle.color("red")
turtle.setup(800, 600)
my_turtle.forward(100)
my_turtle.right(90)
my_turtle.penup()
my_turtle.forward(100)
my_turtle.pendown()
my_turtle.right(90)

my_turtle.forward(100)
my_turtle.right(90)

my_turtle.forward(100)
my_turtle.right(45)
my_turtle.forward(80)

my_turtle.right(97)
my_turtle.forward(70)
my_turtle.right(40)

my_turtle.forward(100)
my_turtle.right(90)
my_turtle.forward(40)
my_turtle.right(85)
my_turtle.forward(30)
my_turtle.left(85)
my_turtle.forward(20)
my_turtle.left(90)
my_turtle.forward(20)

turtle.screensize(6000,7000)
turtle.setup(5000,5000)
turtle.done()